// components/navbar.tsx
import Link from 'next/link';
import { useEffect, useState } from 'react';
import contact from '../data/contact.json';

export default function NavBar() {
  const [theme, setTheme] = useState(String);

  useEffect(() => {
    if (theme === '') {
      setTheme(localStorage.getItem('lynlab.theme') || 'light');
    }
    localStorage.setItem('lynlab.theme', theme);
    theme === 'light' ? document.body.classList.remove('dark') : document.body.classList.add('dark');
  });

  return (
    <div className="w-full h-16 md:h-20 fixed px-4 md:px-8 flex flex-wrap bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-300
                    bg-opacity-80 border-b border-gray-300 dark:border-gray-800 items-center content-center transition-color z-50">
      <div className="flex flex-wrap items-center md:text-lg gap-x-4 tracking-tighter">
        <Link href="/">
          <img className="h-10 md:h-12 w-10 md:w-12 cursor-pointer transition-opacity hover:opacity-50"
               src={`/images/logo-${theme !== 'dark' ? 'black' : 'white'}.png`} alt="lynlab logo" />
        </Link>
        <Link href="/blog">
          <p className="cursor-pointer transition-opacity hover:opacity-50">blog</p>
        </Link>
        <Link href="/resume">
          <p className="cursor-pointer transition-opacity hover:opacity-50">resume</p>
        </Link>
      </div>

      <div className="flex-grow" />

      <div className="hidden mx-4 sm:flex flex-wrap content-center gap-x-4">
        {
          contact.map((item) => (
            <a href={item.link} target="_blank" key={`contact-${item.name}`}
               className="cursor-pointer hover:opacity-50 transition-opacity">
              <i className={`text-xl bi-${item.icon} before:align-middle`} />
            </a>
          ))
        }
      </div>

      <div className="h-8 w-8 rounded-full flex bg-gray-900 text-white dark:bg-white dark:text-gray-900
                      justify-center items-center cursor-pointer hover:opacity-50 transition-opacity"
           onClick={() => setTheme(theme !== 'dark' ? 'dark' : 'light')}>
        {
          theme !== 'dark'
            ? <i className="text-lg bi-moon before:align-middle" />
            : <i className="text-lg bi-brightness-high before:align-middle" />
        }
      </div>
    </div>
  );
}

// components/navbar.vue
<template>
  <div id="navbar" class="flex flex-col">
    <div class="flex flex-col md:flex-row w-full px-4 md:px-6 border-b border-gray-300 text-gray-800 tracking-wider align-middle">
      <div class="flex flex-row font-bold py-4 md:py-6">
        <nuxt-link class="px-1 md:px-2 mt-2 md:mt-1" :to="{ name: 'index' }">
          <img src="/images/logo-black.png" alt="LYnLab Logo" class="h-5 w-10 object-cover">
        </nuxt-link>
        <div class="flex-grow md:hidden" />
        <div class="text-xl md:hidden cursor-pointer" @click="toggleNavbar()">
          <ion-icon name="menu" />
        </div>
      </div>
      <div :class="navbarOpened ? ['flex', 'flex-col'] : ['hidden', 'md:flex']">
        <nuxt-link class="px-1 md:px-2 py-3 md:py-6 hover:text-gray-500" :to="{ name: 'blog' }">Blog</nuxt-link>
        <nuxt-link class="px-1 md:px-2 py-3 md:py-6 hover:text-gray-500" :to="{ name: 'wiki' }">Wiki</nuxt-link>
        <nuxt-link class="px-1 md:px-2 py-3 md:py-6 hover:text-gray-500" :to="{ name: 'resume' }">Resume</nuxt-link>
        <div class="relative px-1 md:px-2 py-3 md:py-6 hover:text-gray-500 cursor-pointer" @click="subnavOpened.apps = !subnavOpened.apps">
          <icon-text v-if="!subnavOpened.apps" icon="caret-down" text="Apps" position="right" />
          <icon-text v-else icon="caret-up" text="Apps" position="right" />
        </div>
      </div>
      <div class="flex-grow" />
      <div :class="navbarOpened ? ['flex'] : ['hidden', 'md:flex']">
        <a class="px-1 py-3 md:py-5 mr-1 text-xl" alt="github" target="_blank" href="https://github.com/hellodhlyn"><ion-icon name="logo-github" /></a>
        <a class="px-1 py-3 md:py-5 mr-1 text-xl" target="_blank" href="https://twitter.com/hellodhlyn"><ion-icon name="logo-twitter" /></a>
        <a class="px-1 py-3 md:py-5 mr-1 text-xl" target="_blank" href="https://instagram.com/hellodhlyn"><ion-icon name="logo-instagram" /></a>
        <a class="px-1 py-3 md:py-5 text-xl" href="mailto:hellodhlyn@gmail.com"><ion-icon name="mail" /></a>
      </div>
    </div>

    <div v-if="subnavOpened.apps" class="flex flex-row px-6 bg-gray-100">
      <p class="px-1 md:px-2 py-3 font-bold">Apps</p>
      <nuxt-link class="px-1 md:px-2 py-3 hover:text-gray-500" :to="{ name: 'apps-crypto' }">CryptoCalc</nuxt-link>
      <a class="px-1 md:px-2 py-3 hover:text-gray-500" href="https://twitdeck.lynlab.co.kr" target="_blank">TwitDeck</a>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      navbarOpened: false,
      subnavOpened: {
        apps: false,
      },
    };
  },
  watch: {
    $route() {
      this.navbarOpened = false;
      this.subnavOpened.apps = false;
    },
  },
  methods: {
    toggleNavbar() {
      if (!this.navbarOpened) {
        this.navbarOpened = true;
      } else {
        this.navbarOpened = false;
        this.subnavOpened.apps = false;
      }
    },
  },
};
</script>
